services:
  postgresdb:
    image: postgres
    environment:
        - POSTGRES_PASSWORD=root
    ports:
        - 5434:5432
    volumes:
        - pgdata:/var/lib/postgresql/data
volumes:
    pgdata: